config:
  choice: ['weighted_scoring'] #'weighted_scoring'
  allocation: ['least_fair', 'product_lottery', 'weighted_product_allocation'] #, 'product_lottery', 'weighted_product_allocation'
  rec_weight: [0.5, 0.7, 1.0, 1.2, 1.4, 2, 5, 7]
  folder_path: "./" 
  base_toml: "movie_individual.toml" 
